"""Initial migration

Revision ID: 9c11ab964345
Revises: 
Create Date: 2026-07-26 05:07:20.789092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c11ab964345'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=True)
    op.create_index(op.f('ix_clients_telegram_chat_id'), 'clients', ['telegram_chat_id'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'AGENT', name='employee_role'), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_phone'), 'employees', ['phone'], unique=True)
    op.create_table('warehouses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('media_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bucket', sa.String(length=255), nullable=False),
    sa.Column('original_object_name', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_object_name', sa.String(length=512), nullable=True),
    sa.Column('content_type', sa.String(length=127), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retail_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('legal_name', sa.String(length=150), nullable=True),
    sa.Column('client_type', sa.Enum('B', 'C', name='client_type'), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('landmark', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('inn', sa.String(length=9), nullable=True),
    sa.Column('checking_account', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=150), nullable=True),
    sa.Column('mfo', sa.String(length=5), nullable=True),
    sa.Column('oked', sa.String(length=5), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('photo_id', sa.UUID(), nullable=True),
    sa.Column('visit_mon', sa.Boolean(), nullable=False),
    sa.Column('visit_tue', sa.Boolean(), nullable=False),
    sa.Column('visit_wed', sa.Boolean(), nullable=False),
    sa.Column('visit_thu', sa.Boolean(), nullable=False),
    sa.Column('visit_fri', sa.Boolean(), nullable=False),
    sa.Column('visit_sat', sa.Boolean(), nullable=False),
    sa.Column('visit_sun', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_employee_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photo_id'], ['media_objects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_retail_points_fri', 'retail_points', ['visit_fri'], unique=False)
    op.create_index('idx_retail_points_mon', 'retail_points', ['visit_mon'], unique=False)
    op.create_index('idx_retail_points_sat', 'retail_points', ['visit_sat'], unique=False)
    op.create_index('idx_retail_points_sun', 'retail_points', ['visit_sun'], unique=False)
    op.create_index('idx_retail_points_thu', 'retail_points', ['visit_thu'], unique=False)
    op.create_index('idx_retail_points_tue', 'retail_points', ['visit_tue'], unique=False)
    op.create_index('idx_retail_points_wed', 'retail_points', ['visit_wed'], unique=False)
    op.create_table('stock_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('RECEIPT', 'RESERVATION', 'CANCEL_RESERVATION', 'SALE', 'WRITEOFF', 'RETURN', 'ADJUSTMENT', name='stock_transaction_type_enum'), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Enum('EMPLOYEE', 'CLIENT', 'SYSTEM', name='transaction_actor_type_enum'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_tx_warehouse_product_created', 'stock_transactions', ['warehouse_id', 'product_id', 'created_at'], unique=False)
    op.create_table('stocks',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_stock_quantity_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('warehouse_id', 'product_id')
    )
    op.create_table('retail_point_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('retail_point_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['retail_point_id'], ['retail_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retail_point_id')
    )
    op.create_index('idx_retail_point_assignment_employee', 'retail_point_assignments', ['employee_id'], unique=False)
    op.create_table('retail_point_invite_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('retail_point_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_code', sa.String(length=512), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_activated_client_id', sa.UUID(), nullable=True),
    sa.Column('last_activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_employee_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['last_activated_client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['retail_point_id'], ['retail_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_index('uq_active_invite_per_retail_point', 'retail_point_invite_codes', ['retail_point_id'], unique=True, postgresql_where=sa.text('is_active = TRUE'))
    op.create_table('retail_point_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('retail_point_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retail_point_id'], ['retail_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('retail_point_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'SKIPPED', name='visit_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['retail_point_id'], ['retail_points.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('retail_point_id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'SHIPPED', 'CANCELLED', name='order_status'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_volume', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['retail_point_id'], ['retail_points.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit_debts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_order', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_volume', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_item_quantity_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('visit_media')
    op.drop_table('visit_debts')
    op.drop_table('orders')
    op.drop_table('visits')
    op.drop_table('retail_point_members')
    op.drop_index('uq_active_invite_per_retail_point', table_name='retail_point_invite_codes', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('retail_point_invite_codes')
    op.drop_index('idx_retail_point_assignment_employee', table_name='retail_point_assignments')
    op.drop_table('retail_point_assignments')
    op.drop_table('stocks')
    op.drop_index('idx_stock_tx_warehouse_product_created', table_name='stock_transactions')
    op.drop_table('stock_transactions')
    op.drop_index('idx_retail_points_wed', table_name='retail_points')
    op.drop_index('idx_retail_points_tue', table_name='retail_points')
    op.drop_index('idx_retail_points_thu', table_name='retail_points')
    op.drop_index('idx_retail_points_sun', table_name='retail_points')
    op.drop_index('idx_retail_points_sat', table_name='retail_points')
    op.drop_index('idx_retail_points_mon', table_name='retail_points')
    op.drop_index('idx_retail_points_fri', table_name='retail_points')
    op.drop_table('retail_points')
    op.drop_table('products')
    op.drop_table('media_objects')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_employees_phone'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_clients_telegram_chat_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('categories')
    # ### end Alembic commands ###
