"""initial_schema_with_stocks

Revision ID: ccafea4ef093
Revises: 
Create Date: 2026-07-20 10:01:42.957969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccafea4ef093'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=True)
    op.create_index(op.f('ix_clients_telegram_chat_id'), 'clients', ['telegram_chat_id'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'AGENT', name='employee_role'), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_phone'), 'employees', ['phone'], unique=True)
    op.create_table('warehouses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retail_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('legal_name', sa.String(length=150), nullable=True),
    sa.Column('client_type', sa.Enum('B', 'C', name='client_type'), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('landmark', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('inn', sa.String(length=9), nullable=True),
    sa.Column('checking_account', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=150), nullable=True),
    sa.Column('mfo', sa.String(length=5), nullable=True),
    sa.Column('oked', sa.String(length=5), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('visit_mon', sa.Boolean(), nullable=False),
    sa.Column('visit_tue', sa.Boolean(), nullable=False),
    sa.Column('visit_wed', sa.Boolean(), nullable=False),
    sa.Column('visit_thu', sa.Boolean(), nullable=False),
    sa.Column('visit_fri', sa.Boolean(), nullable=False),
    sa.Column('visit_sat', sa.Boolean(), nullable=False),
    sa.Column('visit_sun', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_employee_id', sa.UUID(), nullable=True),
    sa.Column('owner_client_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_retail_points_fri', 'retail_points', ['visit_fri'], unique=False)
    op.create_index('idx_retail_points_mon', 'retail_points', ['visit_mon'], unique=False)
    op.create_index('idx_retail_points_sat', 'retail_points', ['visit_sat'], unique=False)
    op.create_index('idx_retail_points_sun', 'retail_points', ['visit_sun'], unique=False)
    op.create_index('idx_retail_points_thu', 'retail_points', ['visit_thu'], unique=False)
    op.create_index('idx_retail_points_tue', 'retail_points', ['visit_tue'], unique=False)
    op.create_index('idx_retail_points_wed', 'retail_points', ['visit_wed'], unique=False)
    op.create_table('stocks',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_stock_quantity_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('warehouse_id', 'product_id')
    )
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('retail_point_id', sa.UUID(), nullable=False),
    sa.Column('actual_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('actual_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('status', sa.Enum('COMPLETED', 'SKIPPED', name='visit_status'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['retail_point_id'], ['retail_points.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('retail_point_id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'SHIPPED', 'CANCELLED', name='order_status'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_volume', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['retail_point_id'], ['retail_points.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_order', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_volume', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_item_quantity_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('visit_photos')
    op.drop_table('orders')
    op.drop_table('visits')
    op.drop_table('stocks')
    op.drop_index('idx_retail_points_wed', table_name='retail_points')
    op.drop_index('idx_retail_points_tue', table_name='retail_points')
    op.drop_index('idx_retail_points_thu', table_name='retail_points')
    op.drop_index('idx_retail_points_sun', table_name='retail_points')
    op.drop_index('idx_retail_points_sat', table_name='retail_points')
    op.drop_index('idx_retail_points_mon', table_name='retail_points')
    op.drop_index('idx_retail_points_fri', table_name='retail_points')
    op.drop_table('retail_points')
    op.drop_table('products')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_employees_phone'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_clients_telegram_chat_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('categories')
    # ### end Alembic commands ###
